services:
  # PostgreSQL DataBase Container
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./script:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    networks:
      default:
        ipv4_address: 192.168.100.3

  # backend
  backend:
    build: ./auth-backend
    container_name: auth-backend
    ports:
      - "8000:8000"
    volumes:
      - ./auth-backend:/code
      - ./.env:/code/.env
    command: ["uvicorn","main:app","--reload","--host","0.0.0.0","--port","8000"]

    depends_on:
      - db

    networks:
      default:
        ipv4_address: 192.168.100.4

  # フロントエンド : frontend
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - auth-backend

  # リバースプロキシ
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
  
    networks:
      default:
        ipv4_address: 192.168.100.6




volumes:
  data:
  
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
  
  