services:
  # PostgreSQL DataBase Container
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./script:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  # backend
  backend:
    build: ./backend
    container_name: auth-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/.env
      - ./.env:/code/.env

    depends_on:
      - db

  # フロントエンド : frontend
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - backend

  # フロントエンド
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html



volumes:
  data:
  
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
  
  